### ISSUE TITLE
hard code?

### ISSUE THREAD

**Issue by MentorTutor** [Ostroumov-Alexander/123#1]
https://github.com/Ostroumov-Alexander/123/blob/72aa50b0964d9333beaf5a8c4e1f7bc1cc791f30/gun.py#L81-L92

**Comment by Ostroumov-Alexander** [comment]
Should I replace "800" and "600" to "WIDTH" and "HEIGHT"?

**Comment by MentorTutor** [comment]
Если это оно, то да. Как вариант.
